version: '3.4'

networks:
  hlf:
    external:
      name: hlf

services:
  couchdb00:
    container_name: couchdb00
    image: hyperledger/fabric-couchdb:0.4.15
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org0
    ports:
            - published: 5984
              target: 5984
              mode: host
    networks:
      - hlf

  couchdb01:
    container_name: couchdb01
    image: hyperledger/fabric-couchdb:0.4.15
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org0
    ports:
            - published: 6984
              target: 5984
              mode: host
    networks:
      - hlf

  couchdb10:
    container_name: couchdb10
    image: hyperledger/fabric-couchdb:0.4.15
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org1
    ports:
            - published: 5984
              target: 5984
              mode: host
    networks:
      - hlf

  couchdb11:
    container_name: couchdb11
    image: hyperledger/fabric-couchdb:0.4.15
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org1
    ports:
            - published: 6984
              target: 5984
              mode: host
    networks:
      - hlf


