version: '3.4'

networks:
  hlf:
    external:
      name: hlf

services:
  org0peer0:
    container_name: peer0.org0
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.3
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.15
      - CORE_PEER_ID=peer0.org0
      - CORE_PEER_ADDRESS=peer0.org0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org0:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0:7051
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb00:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org0/users/:/etc/hyperledger/fabric/users
        - ../crypto-config/peerOrganizations/org0/peers/peer0.org0/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org0/peers/peer0.org0/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
        - ../crypto-config/ordererOrganizations/orderer/orderers/:/etc/hyperledger/orderers
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org0
    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    extra_hosts:
      - "orderer1:10.148.0.11"
      - "orderer2:10.148.0.12"
      - "orderer3:10.148.0.15"
      - "org0:10.148.0.13"
      - "org1:10.148.0.14"
    networks:
      hlf:
        aliases:
          - peer0.org0

  org0peer1:
    container_name: peer1.org0
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.3
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.15
      - CORE_PEER_ID=peer1.org0
      - CORE_PEER_ADDRESS=peer1.org0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org0:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org0:7051
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb01:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org0/users/:/etc/hyperledger/fabric/users
        - ../crypto-config/peerOrganizations/org0/peers/peer1.org0/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org0/peers/peer1.org0/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org0
    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      hlf:
        aliases:
          - peer1.org0

  org1peer0:
    container_name: peer0.org1
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.3
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.15
      - CORE_PEER_ID=peer0.org1
      - CORE_PEER_ADDRESS=peer0.org1:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1/users/:/etc/hyperledger/fabric/users
        - ../crypto-config/peerOrganizations/org1/peers/peer0.org1/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1/peers/peer0.org1/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org1
    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    networks:
      hlf:
        aliases:
          - peer0.org1

  org1peer1:
    container_name: peer1.org1
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.3
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.15
      - CORE_PEER_ID=peer1.org1
      - CORE_PEER_ADDRESS=peer1.org1:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1/users/:/etc/hyperledger/fabric/users
        - ../crypto-config/peerOrganizations/org1/peers/peer1.org1/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1/peers/peer1.org1/tls:/etc/hyperledger/fabric/tls
        - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org1
    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      hlf:
        aliases:
          - peer1.org1

  cli0:
    container_name: cli0
    image: hyperledger/fabric-tools:1.4.3
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli0
      - CORE_PEER_ADDRESS=peer0.org0:7051
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/crypto-config/users/Admin@org0/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org0
    working_dir: /etc/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/chaincode
        - ../crypto-config/peerOrganizations/org0/:/etc/hyperledger/fabric/peer/crypto-config/
    networks:
      hlf:
        aliases:
          - cli0

  cli1:
    container_name: cli1
    image: hyperledger/fabric-tools:1.4.3
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli1
      - CORE_PEER_ADDRESS=peer0.org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/crypto-config/users/Admin@org0/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == org1
    working_dir: /etc/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/chaincode
        - ../crypto-config/peerOrganizations/org1/:/etc/hyperledger/fabric/peer/crypto-config/
    networks:
      hlf:
        aliases:
          - cli1


