version: '2'

networks:
    behave:

services:
  ca2.example.com:
    image: hyperledger/fabric-ca
    environment:
     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=ca2.example.com
     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1-cert.pem
     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d1a26026e1a2af90ff3d3f56f6c9400407b747fdbb825d60e576b4905ce2390b_sk
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1-cert.pem
     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d1a26026e1a2af90ff3d3f56f6c9400407b747fdbb825d60e576b4905ce2390b_sk
    ports:
     - 8054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
     - ./crypto-config/peerOrganizations/org1/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca2.example.com
    networks:
     -  behave




