version: '2'

networks:
    behave:

services:
  peer0.org0:
    container_name: peer0.org0
    image: hyperledger/fabric-peer
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=HLF_behave
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=debug
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=false
    - CORE_PEER_GOSSIP_ORGLEADER=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org0
    - CORE_PEER_ADDRESS=peer0.org0:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_PROFILE_LISTENADDRESS=peer0.org0:6060
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
    - 7051:7051
    - 7053:7053
    - 6060:6060
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org0/users:/var/hyperledger/users
    - ./crypto-config/peerOrganizations/org0/peers/peer0.org0/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org0/peers/peer0.org0/tls:/etc/hyperledger/fabric/tls
    depends_on:
    - couchdb0
    networks:
    - behave

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
    - COUCHDB_USER=
    - COUCHDB_PASSWORD=
    ports:
    - 5984:5984
    networks:
    - behave
    extra_hosts:
     - "orderer1:10.148.0.11"
     - "orderer2:10.148.0.12"
     - "orderer3:10.148.0.15"
     - "org0:10.148.0.13"
     - "org1:10.148.0.14"


