version: '3.4'

networks:
  hlf:
    external:
      name: hlf

services:
  kafka0:
    container_name: kafka0
    image: hyperledger/fabric-kafka:0.4.15
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181
    ports:
      - target: 9092
        published: 9092
        mode: host
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == orderer1
                     # - node.role == manager
    depends_on:
      - zookeeper0
    networks:
      hlf:
        aliases:
          - kafka0

  zookeeper0:
    container_name: zookeeper0
    image: hyperledger/fabric-zookeeper:0.4.15
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == orderer1
                    # - node.role == manager
    ports:
      - target: 2181
        published: 2181
        mode: host
      - target: 2888
        published: 2888
        mode: host
      - target: 3888
        published: 3888
        mode: host
    networks:
      hlf:
        aliases:
          - zookeeper0


